/**
 * AutoGenerated Code By UIPrefabCodeGenerate
 */

using UnityEngine;
using UnityEngine.UI;
using GameUnityFramework.Extensions;

namespace GameGraphics
{
	public class UIViewLoginBase : UIViewBase
	{
		protected Button _buttonNewGameBtn;
		protected virtual void OnButtonNewGameBtnClick(){ }
		protected Button _buttonOldGameBtn;
		protected virtual void OnButtonOldGameBtnClick(){ }
		protected Button _buttonQuitBtn;
		protected virtual void OnButtonQuitBtnClick(){ }
		protected Button _buttonInfoBtn;
		protected virtual void OnButtonInfoBtnClick(){ }
		protected Button _buttonSettingBtn;
		protected virtual void OnButtonSettingBtnClick(){ }
		protected override void BindWidgets()
		{
			_buttonNewGameBtn = _root.transform.Find("<Button>NewGameBtn").GetComponent<Button>();
			_buttonNewGameBtn.onClick.AddListener(OnButtonNewGameBtnClick);
			_buttonOldGameBtn = _root.transform.Find("<Button>OldGameBtn").GetComponent<Button>();
			_buttonOldGameBtn.onClick.AddListener(OnButtonOldGameBtnClick);
			_buttonQuitBtn = _root.transform.Find("<Button>QuitBtn").GetComponent<Button>();
			_buttonQuitBtn.onClick.AddListener(OnButtonQuitBtnClick);
			_buttonInfoBtn = _root.transform.Find("<Button>InfoBtn").GetComponent<Button>();
			_buttonInfoBtn.onClick.AddListener(OnButtonInfoBtnClick);
			_buttonSettingBtn = _root.transform.Find("<Button>SettingBtn").GetComponent<Button>();
			_buttonSettingBtn.onClick.AddListener(OnButtonSettingBtnClick);
		}
		protected override string GetPrefabPath()
		{
			return "Prefabs/UIView/UIViewLogin.prefab";
		}
	}
}
