/**
 * AutoGenerated Code By UIPrefabCodeGenerate
 */

using UnityEngine;
using UnityEngine.UI;
using GameUnityFramework.Extensions;

namespace GameGraphics
{
	public class UIViewLoginBase : UIViewBase
	{
		protected Button _buttonStart;
		protected virtual void OnButtonStartClick(){ }
		protected override void BindWidgets()
		{
			_buttonStart = _root.transform.Find("Image/<Button>Start").GetComponent<Button>();
			_buttonStart.onClick.AddListener(OnButtonStartClick);
		}
		protected override string GetPrefabPath()
		{
			return "Prefabs/UIView/UIViewLogin.prefab";
		}
	}
}
