/**
 * AutoGenerated Code By UIPrefabCodeGenerate
 */

using UnityEngine;
using UnityEngine.UI;
using GameUnityFramework.Extensions;

namespace GameGraphics
{
	public class UIViewDeveloperInfoBase : UIViewBase
	{
		protected Button _buttonPanel;
		protected virtual void OnButtonPanelClick(){ }
		protected GameObject _gameobjectDeveloperInfoPanel;
		protected override void BindWidgets()
		{
			_buttonPanel = _root.transform.Find("<Button>Panel").GetComponent<Button>();
			_buttonPanel.onClick.AddListener(OnButtonPanelClick);
			_gameobjectDeveloperInfoPanel = _root.transform.Find("<GameObject>DeveloperInfoPanel").gameObject;
		}
		protected override string GetPrefabPath()
		{
			return "Prefabs/UIView/UIViewDeveloperInfo.prefab";
		}
	}
}
