/**
 * AutoGenerated Code By UIPrefabCodeGenerate ==> CodeGenerate
 */

using System;
using System.Collections.Generic;

namespace GameGraphics
{
	public partial class UIViewConfig
	{
		public static Dictionary<string, Type> NameToTypeDict = new Dictionary<string, Type>()
		{
			{"UIViewLogin", typeof(UIViewLogin)},
			{"UIViewSetting", typeof(UIViewSetting)},
			{"UIViewDeveloperInfo", typeof(UIViewDeveloperInfo)},
			{"UIViewGameSave", typeof(UIViewGameSave)},
			{"UIViewExtra", typeof(UIViewExtra)},
		};
	}
}
