/**
 * AutoGenerated Code By UIPrefabCodeGenerate
 */

using UnityEngine;
using UnityEngine.UI;
using GameUnityFramework.Extensions;

namespace GameGraphics
{
	public class UIViewGameSaveBase : UIViewBase
	{
		protected Button _buttonPanel;
		protected virtual void OnButtonPanelClick(){ }
		protected GameObject _gameobjectSettingPanel;
		protected Button _buttonRead;
		protected virtual void OnButtonReadClick(){ }
		protected Button _buttonDelete;
		protected virtual void OnButtonDeleteClick(){ }
		protected Button _buttonSlot_1;
		protected virtual void OnButtonSlot_1Click(){ }
		protected Button _buttonSlot_2;
		protected virtual void OnButtonSlot_2Click(){ }
		protected Button _buttonSlot_3;
		protected virtual void OnButtonSlot_3Click(){ }
		protected override void BindWidgets()
		{
			_buttonPanel = _root.transform.Find("<Button>Panel").GetComponent<Button>();
			_buttonPanel.onClick.AddListener(OnButtonPanelClick);
			_gameobjectSettingPanel = _root.transform.Find("<GameObject>SettingPanel").gameObject;
			_buttonRead = _root.transform.Find("<GameObject>SettingPanel/Button/<Button>Read").GetComponent<Button>();
			_buttonRead.onClick.AddListener(OnButtonReadClick);
			_buttonDelete = _root.transform.Find("<GameObject>SettingPanel/Button/<Button>Delete").GetComponent<Button>();
			_buttonDelete.onClick.AddListener(OnButtonDeleteClick);
			_buttonSlot_1 = _root.transform.Find("<GameObject>SettingPanel/Save/<Button>Slot_1").GetComponent<Button>();
			_buttonSlot_1.onClick.AddListener(OnButtonSlot_1Click);
			_buttonSlot_2 = _root.transform.Find("<GameObject>SettingPanel/Save/<Button>Slot_2").GetComponent<Button>();
			_buttonSlot_2.onClick.AddListener(OnButtonSlot_2Click);
			_buttonSlot_3 = _root.transform.Find("<GameObject>SettingPanel/Save/<Button>Slot_3").GetComponent<Button>();
			_buttonSlot_3.onClick.AddListener(OnButtonSlot_3Click);
		}
		protected override string GetPrefabPath()
		{
			return "Prefabs/UIView/UIViewGameSave.prefab";
		}
	}
}
