/**
 * AutoGenerated Code By UIPrefabCodeGenerate
 */

using UnityEngine;
using UnityEngine.UI;
using GameUnityFramework.Extensions;

namespace GameGraphics
{
	public class UIViewExtraBase : UIViewBase
	{
		protected Button _buttonSettingBtn;
		protected virtual void OnButtonSettingBtnClick(){ }
		protected Text _textLevel;
		protected Button _buttonAddLevel;
		protected virtual void OnButtonAddLevelClick(){ }
		protected override void BindWidgets()
		{
			_buttonSettingBtn = _root.transform.Find("<Button>SettingBtn").GetComponent<Button>();
			_buttonSettingBtn.onClick.AddListener(OnButtonSettingBtnClick);
			_textLevel = _root.transform.Find("Info/<Text>Level").GetComponent<Text>();
			_buttonAddLevel = _root.transform.Find("<Button>AddLevel").GetComponent<Button>();
			_buttonAddLevel.onClick.AddListener(OnButtonAddLevelClick);
		}
		protected override string GetPrefabPath()
		{
			return "Prefabs/UIView/UIViewExtra.prefab";
		}
	}
}
